name: newsapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  assets:
    - assets/


  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat-Regular.ttf
        - asset: lib/fonts/Montserrat-Bold.ttf
        - asset: lib/fonts/Montserrat-Italic.ttf
        - asset: lib/fonts/Montserrat-BoldItalic.ttf
        - asset: lib/fonts/Montserrat-ExtraBold.ttf
        - asset: lib/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: lib/fonts/Montserrat-Light.ttf
        - asset: lib/fonts/Montserrat-LightItalic.ttf
        - asset: lib/fonts/Montserrat-Medium.ttf
        - asset: lib/fonts/Montserrat-MediumItalic.ttf
        - asset: lib/fonts/Montserrat-SemiBold.ttf
        - asset: lib/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: lib/fonts/Montserrat-Thin.ttf
        - asset: lib/fonts/Montserrat-ThinItalic.ttf
        - asset: lib/fonts/Montserrat-Black.ttf
        - asset: lib/fonts/Montserrat-BlackItalic.ttf
        - asset: lib/fonts/Montserrat-ExtraLight.ttf
        - asset: lib/fonts/Montserrat-ExtraLightItalic.ttf